### ISSUE TITLE
Cliqz does not respect the browser search settings and force the cliqz addons ones

### ISSUE THREAD

**Issue by milouse** [cliqz-oss/browser-f#1096]
I'm using a nightly build of Cliqz, compiled against the commit e59bb753d337671d9723fd2bf5ea65a65ada6b21.

about:support displays the following info:

**Version** 1.24.0
**Build ID** 20190101222708
**Cliqz (Nightly)** 1.33.0.388 cliqz@cliqz.com

In the search settings of the browser, I've setup a custom search engine, as displayed in the following screenshot
![capture du 2019-01-02 16-13-00](https://user-images.githubusercontent.com/349239/50597918-5af86180-0ea9-11e9-8a26-3607be556bed.png)

But entering any content in the URL bar will default instead on Google, which is the default search engine of the Cliqz addons:
![capture du 2019-01-02 16-14-55](https://user-images.githubusercontent.com/349239/50597976-8ed38700-0ea9-11e9-9498-b00c74dee351.png)

# Expected result

The alternative search engine list of the addons should be the same as the search engine list of the browser itself, and the selected default one should be the one chosen for the browser.

# Observed result

The cliqz addons ignores the browser settings and prevent the user to add custom search engines.

**Comment by kateryna-cliqz** [comment]
Thanks for the detailed report!
We were able to reproduce the issue and appropriate ticket was created. 
The issue will be fixed in nearest release version.  

Best regards,
Kateryna (Cliqz QA Team)

**Comment by luciancor** [comment]
@alver-cliqz this issue was in the extension and we fixed it 1 week ago. it is already fixed on beta and will go live in production witn 1.33.0 at the beginning of next week

**Comment by milouse** [comment]
I confirm the fix in the 1.25.0 release embedding cliqz addons v1.33.0 .
