### ISSUE TITLE
Current tab is almost invisible with the dark theme, without the blue bar

### ISSUE THREAD

**Issue by milouse** [cliqz-oss/browser-f#1097]
I'm using a nightly build of Cliqz, compiled against the commit e59bb75.

about:support displays the following info:

**Version** 1.24.0
**Build ID** 20190101222708
**Cliqz (Nightly)** 1.33.0.388 cliqz@cliqz.com

# Expected result

The current tab should be easily spotable on the tab bar

# Actual result

There is no difference between the current tab and the other background tabs, as seen in the following screenshot

![capture du 2019-01-02 16-21-48](https://user-images.githubusercontent.com/349239/50598259-84fe5380-0eaa-11e9-95a3-38edc5a278f9.png)

**Comment by milouse** [comment]
I was off for some days, I just came back and just saw the new release :)

I can already confirm that it's ok with the .deb release. I'm waiting for the end of the compilation to check if it's fixed in all cases, but I think there will be no problem.

Thanks :)

**Comment by alver-cliqz** [comment]
@milouse good to know. Thank you for your help
