### ISSUE TITLE
Browser icon

### ISSUE THREAD

**Issue by alver-cliqz** [cliqz-oss/browser-f#11]
![7](https://cloud.githubusercontent.com/assets/14071898/10391829/ed2be46c-6e81-11e5-945f-a1a1a6d7b0a3.PNG)
![8](https://cloud.githubusercontent.com/assets/14071898/10391830/ed2eba48-6e81-11e5-8b93-0d6b99aa4d95.PNG)

Now it's look much better than black one :) Look in attaches, please. It still can be little confusing to find Cliqz icon on some backgrounds. Browser could be installed in millions of PC. Default background on Windows platform use different colors in blue. Also user's usually replace background with their own (and it could be a lot of sky on their pictures). Can we improve icon somehow? For example create small white glow, like CocCoc browser? Firefox and Chrome doesn't have such kind of problem, because they use a lot of colors in their logos.

**Comment by chrmod** [comment]
waits for Valeria

**Comment by stefanie-cliqz** [comment]
Design team is going through some general branding decisions at the moment, taking the whole product portfolio into consideration. This will take some time. Will move this ticket to backlog to be considered again in a few weeks, possibly at the end of Q1.

**Comment by chrmod** [comment]
moved to jira
