### ISSUE TITLE
Browser crashes

### ISSUE THREAD

**Issue by stefanie-cliqz** [cliqz-oss/browser-f#111]
Users have reported that their CLIQZ browser crashed. This ticket will collect all information we receive.

1. Reported by @ilaria-cliqz:

"If I try to open this link: http://nationalesuisse.nsp-reports.ch/13/Finanzbericht/files/assets/basic-html/page24.html Cliqz crashes and I have to force the quit.

This webpage works fine on Chrome (a bit slow actually, but not crash)."

I (Stefanie) could reproduce using CLIQZ 0.8.3.
 

2. External user with **Windows Vista** reported crashes (no further details so far).

**Comment by alver-cliqz** [comment]
Similar problem in original FF. May be create a bug in FF bugtracker?

**Comment by chrmod** [comment]
moved to jira
