### ISSUE TITLE
The developer console use default webfont family (proportional) instead of monospace

### ISSUE THREAD

**Issue by milouse** [cliqz-oss/browser-f#1110]
The web developer console seems to use the browser default font (serif or sans-serif), but not a monospaced one. This behavior differ from firefox, where the webdeveloper font is fixed.

Here is a screenshot of my current console:
![capture du 2019-01-14 08-41-08](https://user-images.githubusercontent.com/349239/51101024-ba6f3f00-17d0-11e9-8949-52841dad92b1.png)

**Comment by remusao** [comment]
@milouse On Ubuntu I do not seem to have this issue, could it be some fonts are not installed on your system?

**Comment by milouse** [comment]
Ok I'll look at the css file. It may be a problem of default font… I'll let you know if I find something.

**Comment by milouse** [comment]
The problem only occurs with the compiled version of cliqz. Not with the repackaged deb. I'll try to diff the two directories.

**Comment by milouse** [comment]
I think I'll close this issue for now. I've take time to compare both resources files, and nothing seems wrong or specifically font related. I still have the problem, but now it's cause is more obvious: I compile my own version of cliqz on machine A, and install the same package on all my computers. The problem is fixed on machine A but continue on all others. I think it is related to my local environment during compilation. When I'll have time, I'll try to do proper build in a chrooted environment.

Sorry for the noise.

**Comment by milouse** [comment]
I confirm the problem comes from my local environment. Building cliqz in chroot made the problem disapear. Sorry for the noise.

**Comment by alver-cliqz** [comment]
Good to know that this one fixed. Thank you for you help!
