### ISSUE TITLE
russian l10n

### ISSUE THREAD

**Issue by Krotesk1** [cliqz-oss/browser-f#1174]
Please add Russian localization.

**Comment by Krotesk1** [comment]
Created a fork - try to understand yourself.

**Comment by alver-cliqz** [comment]
Hello. We do not planning to support russian localization for now. You can try, it is simple - just download proper l10n from https://hg.mozilla.org/l10n-central/ru/, checkout proper version (mozilla-release\browser\locales\l10n-changesets.json), put in into l10n/ru folder. Then you need to make changes in build script, check all mentions of CQZ_BUILD_DE_LOCALIZATION and change de to ru (don't need to change env-variable name). To build - don't forget to set CQZ_BUILD_DE_LOCALIZATION variable to 1. Good luck. All texts, without russian translation, will be in English.

**Comment by milouse** [comment]
I've succeeded to build a french release of cliqz. Here are my exact step:

```bash
# Declare my building locale
_otherlocale=fr
# Found the correct commit id in mozilla-release\browser\locales\l10n-changesets.json
# For french it's:
_otherlocale_ci=03cce8938e38
# Download it
curl -O "https://hg.mozilla.org/l10n-central/${_otherlocale}/archive/${_otherlocale_ci}.tar.bz2"
tar xjf "${_otherlocale_ci}.tar.bz2"
# I extract cliqz source code in `cliqz`
cd cliqz
sed -i "s/mach build installers-de/mach build installers-${_otherlocale}/" magic_build_and_package.sh
sed -i "s/full-update AB_CD=de/full-update AB_CD=${_otherlocale}/" magic_upload_files.sh
sed -i "s/export LANG='de'/export LANG='${_otherlocale}'/" magic_upload_files.sh
cp -R "../${_otherlocale}-${_otherlocale_ci}" "l10n/${_otherlocale}"

# Time to build
export CQZ_BUILD_DE_LOCALIZATION=1
export LANG="${_otherlocale}"
./magic_build_and_package.sh
```

Your newly built package should be `obj/dist/$pkgname-$pkgver.${_otherlocale}.linux-x86_64.tar.bz2`

Of course you may need to modify other things to successfully build cliqz (like the mozilla and google api keys, etc.)
