### ISSUE TITLE
View source and responsive tool result in a blank tab on linux

### ISSUE THREAD

**Issue by milouse** [cliqz-oss/browser-f#1176]
The problem both occurs for me using the unpacked *.deb version or my own compiled version.

about:support displays the following info:

**Version** 1.25.1
**Build ID** 20190213162449
**Cliqz** 1.33.0 cliqz@cliqz.com

## Expected result

1. When hitting `ctrl+U` or right click anywhere on the page and selecting « View Page Source », it must open a new tab containing the same visited URL, prefixed by `view-source:`
2. When hitting `ctrl+shift+M` or clicking on the related button in the developper web console, it must replace the current viewport with the responsive tool.

## Actual result

1. A new blank tab is opened. Although this new tab just pop up, it already has an history attached to it. Going backward (by clicking the « back arrow for example ») actually display the `view-source:` page.
2. The current viewport goes blank. Trying to go back will change the URL in the URL bar as expected, but leave the viewport blank, keeping us stuck in this blank mode: the browser has switched internally in responsive mode, but as the UI is not loaded, it is not possible to escape of it (it is viewable in the old menu bar, in the « Tools » menu, then « Web Developper » : the « Responsive Design Mode » is checked, but it is not possible to uncheck it). I've found no workaround for this.

**Comment by alver** [comment]
Hi! Knowing issue, we are releasing 1.25.2 today with fix for both

**Comment by milouse** [comment]
I confirm this is closed by the latest release. Thank you very much!
