### ISSUE TITLE
Add build number into Cliqz

### ISSUE THREAD

**Issue by alver-cliqz** [cliqz-oss/browser-f#120]
We need somehow translate internal build number from Jenkins into browser build, so later to be able to see this number in crash reports and telemetry

**Comment by luciancor** [comment]
+ the installers  should contain the build number (see screenshot)
![screen shot 2016-01-14 at 09 08 06](https://cloud.githubusercontent.com/assets/5583036/12319715/75fe38a8-baa4-11e5-8e42-7272eba318ae.png)

**Comment by chrmod** [comment]
moved to jira
