### ISSUE TITLE
Silverlight not working - plugin not installed in our browser

### ISSUE THREAD

**Issue by luciancor** [cliqz-oss/browser-f#124]
In firefox:

<img width="389" alt="screen shot 2016-01-14 at 16 23 00" src="https://cloud.githubusercontent.com/assets/5583036/12328318/28c04248-badb-11e5-9e4c-19befcb87ef6.png">

<img width="1438" alt="screen shot 2016-01-14 at 16 23 20" src="https://cloud.githubusercontent.com/assets/5583036/12328319/2904f492-badb-11e5-94c8-dc58969a70b2.png">

**Comment by chrmod** [comment]
moved to jira
