### ISSUE TITLE
Unable to download the plugins during build time after Cliqz 1.26.5 update

### ISSUE THREAD

**Issue by fraggerfox** [cliqz-oss/browser-f#1253]
Hello

I was trying to build Cliqz-1.26.5 after the release, and I came across a problem when it tried to download the various `xpi` plugins. It seems the URL gives a 404 when I attempt to download them.

Here are logs from an attempt.

First I tried to get the `lastbuildid`, which worked.
```
# ftp -Vo - https://repository.cliqz.com/dist/release/1.26.5/lastbuildid
20190508134915
#
```

Then using that I tried to download the plugin and that shows a 404.

```
# ftp https://repository.cliqz.com/dist/release/1.26.5/20190508134915/cliqz@cliqz.com.xpi
Trying 13.35.253.123:443 ...
Requesting https://repository.cliqz.com/dist/release/1.26.5/20190508134915/cliqz@cliqz.com.xpi
ftp: Error retrieving file `404 Not Found'
#
```
Do let me know if I am doing something wrong or if something has changed between the releases Cliqz-1.26.4 and Cliqz-1.26.5.

Thank you.

**Comment by alver-cliqz** [comment]
Good day. Thank you for pointing to this, I need to make some changes in build scripts.

Problem fixed for now, please check again

**Comment by fraggerfox** [comment]
Looks like it works now, I am able to download the plugins as expected.

Thank you @alver-cliqz 

Closing this ticket, since it is resolved.
