### ISSUE TITLE
Please add a tag for the 1.27.3 release

### ISSUE THREAD

**Issue by milouse** [cliqz-oss/browser-f#1286]
In order to ease other packaging of the mozilla quick fix for the 0-day. Thank you very much.

**Comment by aleksei-cliqz** [comment]
Thank you @milouse for notification.
Done.

**Comment by milouse** [comment]
Don't forget to move the debian build from the prerelease repository to the release one!

**Comment by alver-cliqz** [comment]
Everything done on Friday

**Comment by alver-cliqz** [comment]
@milouse please re-check your build, because I recreated a tag (aleksei put a wrong one). Sorry for mess

**Comment by milouse** [comment]
Ok thanks for the notification, I'll look at it tomorrow.

**Comment by milouse** [comment]
Is the 1.27.4 release ready as well? It shows off on your repository, but not as a debian release nor a tag?

**Comment by alver-cliqz** [comment]
In progress, testing today (we found one more minor bug, want to put into release also). You can check current release branch, I will put a new tag asap after internal testing
