### ISSUE TITLE
Pre set Bookmarks

### ISSUE THREAD

**Issue by luciancor** [cliqz-oss/browser-f#129]
For english build:
"Tipps und Tricks page" is in German
 "About Us" page is in German
“Team" leads to a NOT FOUND page in German (!)

**Comment by chrmod** [comment]
Where we set default bookmarks ATM?

We should probably use distribution.ini for this purpose and create separate distribution file for each supported language. 

Another workaround would be to have language detection on a website, so we can have one link for all languages - this does not solve the problem of link label though.

**Comment by luciancor** [comment]
@stefanie-cliqz the website needs to have a valid url (or redirect) for https://cliqz.com/team/ as it is used both in the browser and the extension

**Comment by luciancor** [comment]
@chrmod language detection should be handled on the website and the labels are handled with the normal localization mechanisms eg:  https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/locales/generic/profile/bookmarks.html.in#L23

**Comment by stefanie-cliqz** [comment]
Thanks, @luciancor 
the link on the website is https://cliqz.com/aboutus/team (German) and https://cliqz.com/en/aboutus/team (English). Can you change this URL in the browser and extension? 
Alternatively we can add redirects to the website, however, the more redirects, the more error-prone. Therefore option 1 would be preferred.

**Comment by chrmod** [comment]
moved to jira
