### ISSUE TITLE
Dark Reader extension incompatible with Cliqz browser

### ISSUE THREAD

**Issue by shscs911** [cliqz-oss/browser-f#1290]
[Dark Reader](https://addons.mozilla.org/en-US/firefox/addon/darkreader/) extension can't be installed in Cliqz. It gives the error `Cliqz does not support some APIs for reasons of privacy protection and performance`. But the addon [Dark Night Mode](https://addons.mozilla.org/en-US/firefox/addon/dark-night-mode/) providing similar function can be installed. I love the preview in the search bar and anti-tracker functions. Incompatibility with <b>Dark Reader</b> is the only reason I haven't switched to <b>Cliqz</b> as a full-time browser.

**Comment by alver-cliqz** [comment]
@tsl143 , which API this extension need, which we don't support?

**Comment by tsl143** [comment]
Dark reader uses `theme` API which we don't support.

**Comment by remusao** [comment]
@shscs911 @tsl143 @alver-cliqz As far as I can see, `Dark Reader` can now be installed in Cliqz and works properly (I tried just now). Could you please confirm that the issue is resolved on your side as well?

**Comment by shscs911** [comment]
@remusao Thanks, mate. `Dark Reader` is working now. Marking issue as closed.
