### ISSUE TITLE
Help menu lost CLIQZ entries

### ISSUE THREAD

**Issue by luciancor** [cliqz-oss/browser-f#130]
Help menu is not providing the CLIQZ tour, nor other CLIQZ features

**Comment by chrmod** [comment]
@richard-cliqz @robert-cliqz please include testing of help menu in our QA procedure

**Comment by richard-cliqz** [comment]
Already is included.


---- Krzysztof Jan Modras schrieb ----


@richard-cliqz<https://github.com/richard-cliqz> @robert-cliqz please include testing of help menu in our QA procedure

-

**Comment by roberto-cliqz** [comment]
Help Menu is to be tested in the entry 0.8.1-013  "Top and Burger Menu (Help / Questionmark)".

**Comment by chrmod** [comment]
moved to jira
