### ISSUE TITLE
"Publisher unknown" warning when installing update

### ISSUE THREAD

**Issue by richard-cliqz** [cliqz-oss/browser-f#135]
See screenshot.
Reproduce:
Wait until receiving update notification,
closing CLIQZ
opening CLIQZ
the attached warning message is given

expected behavior:
Program name should be "CLIQZ"
Publisher should be "Cliqz GmbH"

Windows 10
![dsc_0002 7](https://cloud.githubusercontent.com/assets/6839735/12379969/c1b8aa5c-bd66-11e5-926c-16215aea50a4.JPG)

**Comment by chrmod** [comment]
moved to jira
