### ISSUE TITLE
Github release tag and version mismatch

### ISSUE THREAD

**Issue by fraggerfox** [cliqz-oss/browser-f#1387]
I have a problem trying to update the cliqz packages in FreeBSD. This is due to the fact that there is a version mismatch between the tag and the version of cliqz.

`https://github.com/cliqz-oss/browser-f/tree/1.30.1`

The release tag is currently set to `1.30.1` and the release version number is indicated as `1.30.0` due to which the Github fetch fails because it cannot find the tag `1.30.0` or the attempt to get the browser extensions fail which uses `1.30.1` when it tries to download them (if the github tag is set to point to `1.30.1` from the ports `Makefile` script).

For example 

`https://repository.cliqz.com/dist/release/1.30.0/lastbuildid` 

gives me the correct `lastbuildid` but

`https://repository.cliqz.com/dist/release/1.30.1/lastbuildid`

gives me a `NoSuchKey` error.

FreeBSD packages require one canonical version number to be mentioned for the package and this mismatch is preventing things from being updated in the cliqz port for FreeBSD.

What is the suggested solution to the above mismatch in tag and version numbers?

**Comment by tsl143** [comment]
Hi @fraggerfox thank you for pointing this out.
I have updated the release tag, please let me know it you face any more issue.

**Comment by fraggerfox** [comment]
@tsl143 Thanks for the update.

Looks like this fixes the issue I was facing and I am able to update the package.

Closing the ticket as the problem is resolved.
