### ISSUE TITLE
cliqz 1.32.0-1 terminated by signal SIGSEGV (Address boundary error) on Debian Testing

### ISSUE THREAD

**Issue by muusik** [cliqz-oss/browser-f#1434]
This bug is incomplete. Please let me know what useful information can be added.

**Comment by remusao** [comment]
Hi @muusik,

Thanks for taking the time to report the issue. We are aware of this issue and working on fixing it ASAP. Sorry for the inconvenience caused by the crash.

Best,

**Comment by remusao** [comment]
@muusik We identified and fixed the issue. We need to perform a bit of extra testing to make sure there is no regression then we will prepare a release. Thanks a lot for your patience.

**Comment by remusao** [comment]
@muusik We have published a new stable release of Cliqz for Linux a few minutes ago. This should fix the crash on start-up that you experienced. Let me know if there is anything else!

**Comment by muusik** [comment]
I have installed the new version and it works perfectly. Thank you again.
