### ISSUE TITLE
cliqz quits with error after a most recent upgrade

### ISSUE THREAD

**Issue by sudoyang** [cliqz-oss/browser-f#1435]
➜  ~ cliqz    

(cliqz:26696): Gtk-WARNING **: 19:00:24.656: Theme parsing error: gtk.css:1:104: Failed to import: Error opening file /home/phy/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/buttons-left.css: No such file or directory
JavaScript warning: resource://gre/modules/TelemetryReportingPolicy.jsm, line 413: unreachable code after return statement
JavaScript warning: chrome://browser/content/browser.js, line 4278: unreachable code after return statement

(/usr/local/lib/cliqz/cliqz:26753): Gtk-WARNING **: 19:00:26.050: Theme parsing error: gtk.css:1:104: Failed to import: Error opening file /home/phy/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/buttons-left.css: No such file or directory
JavaScript warning: chrome://extensions/content/parent/ext-theme.js, line 458: unreachable code after return statement
JavaScript warning: chrome://extensions/content/parent/ext-theme.js, line 475: unreachable code after return statement
Exiting due to channel error.
[1]    26696 segmentation fault (core dumped)  cliqz

➜  ~ cliqz -v
Cliqz GmbH Cliqz 1.32.0

**Comment by Filbuntu** [comment]
Same here on Ubuntu 19.10 (1.32.0-1). I can not even start it on safe-mode:
$ cliqz -safe-mode
JavaScript warning: resource://gre/modules/TelemetryReportingPolicy.jsm, line 413: unreachable code after return statement
JavaScript warning: chrome://extensions/content/parent/ext-theme.js, line 458: unreachable code after return statement
JavaScript warning: chrome://extensions/content/parent/ext-theme.js, line 475: unreachable code after return statement
JavaScript warning: chrome://browser/content/browser.js, line 4278: unreachable code after return statement
Segmentation fault (core dumped)

I don't want to refresh Cliqz and lose all the settings. Therefore I hope there will be a way to address. Thanks!

**Comment by remusao** [comment]
Hi there,

Thanks a lot for opening an issue and giving details. We are aware of the issue and working on fixing it ASAP. Apologies for the inconvenience caused.

Best,

**Comment by remusao** [comment]
@sudoyang @Filbuntu We identified and fixed the issue. We need to perform a bit of extra testing to make sure there is no regression then we will prepare a release. Thanks a lot for your patience.

**Comment by Filbuntu** [comment]
@remusao Thanks a lot for the speedy fix! I am looking forward to the release!

**Comment by remusao** [comment]
@sudoyang @Filbuntu We have published a new stable release of Cliqz for Linux a few minutes ago. This should fix the crash on start-up that you experienced. Let me know if there is anything else!

**Comment by sudoyang** [comment]
Thank a lot!

**Comment by Filbuntu** [comment]
@remusao  Thank you for the swift fix! I could download it yesterday but had no time to text properly as I was travelling. It works for me and I can use Cliqz again, hurray! Thanks again!
