### ISSUE TITLE
Low text contrast in Settings: Labs

### ISSUE THREAD

**Issue by da2x** [cliqz-oss/browser-f#1478]
<img width="1392" alt="contrast" src="https://user-images.githubusercontent.com/1102886/75718040-90c5ef80-5cd2-11ea-9ece-6ca9246220fe.png">

Cliqz 1.33.0, macOS 10.15.3

**Comment by alver-cliqz** [comment]
@sammacbeth please fix this.
@da2x thank you for report!

**Comment by sammacbeth** [comment]
This is because the settings UI is responsive to 'dark mode' being enabled in the OS, while the dat-webext settings are not. This can be fixed entirely in that project.

**Comment by alver-cliqz** [comment]
@da2x please try to force update (opening Cliqz -> About from system menu or Preferences page will do this) and check for fix

**Comment by da2x** [comment]
The text is set with a legible contrast after force-updating. The page uses different checkbox-styles from the other settings (you can see that on the above screenshot), but that is a trivial issue.

**Comment by alver-cliqz** [comment]
Ok, thank you
