### ISSUE TITLE
Cliqz browser doesn't close when trying to load a huge page

### ISSUE THREAD

**Issue by khaled-cliqz** [cliqz-oss/browser-f#16]
https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-abstract14.xml

this url contains a 200+ MB xml file, when I opened it, it was loading for a long time.
then I closed the tab, it kept opening again and kept trying to load the page.
and after time browser became very heavy and hanged

N.B: thanks to @luciancor we found out that the bug also occurs on firefox.

**Comment by chrmod** [comment]
that's firefox issue, report to mozilla please :-)
