### ISSUE TITLE
"Standard-Suchmaschine"

### ISSUE THREAD

**Issue by chrmod** [cliqz-oss/browser-f#20]
Original issue: https://github.com/cliqz/browser-feedback/issues/85
Reporter: javier-cliqz

![d9abb768-7733-11e5-8c42-84a1a16f3d9a](https://cloud.githubusercontent.com/assets/1228153/10606640/93d63c80-7734-11e5-9971-06f4fe746d67.png)

bildschirmfoto 2015-10-20 um 13 57 16

As you can see, we still refer to other search engines as "standard". The standard search engine in the Cliqz Browser is Cliqz (obviously), but we inherit this naming convention from Firefox. I would feel more comfortable calling them secondary/complementary search engines.

@thomask-cliqz @richard-cliqz

**Comment by richard-cliqz** [comment]
Change wording here and in BROWSER OPTIONS --> SEARCH: "Default search engine" to "Complementary search engine" / "Ergänzende Suchmaschine"

**Comment by chrmod** [comment]
duplicate of https://github.com/cliqz-oss/browser-f/issues/54
