### ISSUE TITLE
 Page loading forever

### ISSUE THREAD

**Issue by chrmod** [cliqz-oss/browser-f#25]
Original issue: https://github.com/cliqz/browser-feedback/issues/42
Reporter: eleniS

URL: http://www.cultofmac.com/311018/apple-may-take-google-search-engine/

Loads correctly on Firefox.

Version: 39.0
Cliqz 1.0

Another example:
http://www.mactrast.com/2012/07/how-to-use-do-not-disturb-mode-in-the-os-x-mountain-lion-notification-center/

First example loads correctly on a private window.
The second one is loading forever.

**Comment by chrmod** [comment]
@konark-cliqz please take a look on this one

**Comment by chrmod** [comment]
@konark-cliqz ping

**Comment by luciancor** [comment]
@chrmod these types of problems are usually related with the user profile. Firefox caches some urls in some redirects and this can cause infinite loops. @eleniS can you please load that url in a private window in the CLIQZ browser?

**Comment by konark-cliqz** [comment]
@luciancor @chrmod : I was only able to replicate the second URL, and that too in firefox, where it looks it is loading forever.

I want to debug this a bit in detail, so as to see that this is not because of Anti-tracking. As I partially saw different behaviour with and without our anti-tracking.

**Comment by stefanie-cliqz** [comment]
Firefox/profile problem. Closing issue.
