### ISSUE TITLE
 Cliqz still send request to mozilla repair

### ISSUE THREAD

**Issue by chrmod** [cliqz-oss/browser-f#27]
Original issue: https://github.com/cliqz/browser-feedback/issues/18
Reporter:  zhonghao-cliqz

https://self-repair.mozilla.org/en-US/repair

**Comment by alver-cliqz** [comment]
Good&bad news.

Good. Looks like all url are placed in one place - mozilla-release\browser\app\profile\firefox.js. This self-repair url exist in it file too.

Bad. In this file tons of different urls. Some of them are self-described, but here a lot of urls to some FF services, and we need some time to understand what we need and must replace, what we don't need at all and which part we don't care at all.

I think we need to investigate some of the most dangerous link for our product (like self-repair, different blocklists, update urls, safe-browsing urls, crash-report url, etc.). All this not looking like "the latest browser you will install for you parent" for now. We need to talk about this a lot

**Comment by chrmod** [comment]
alright, closing this one for now. What we need to do to is to investigate more and decide on what our focus should be

**Comment by alver-cliqz** [comment]
Some information (start point for future researchers generation) in wiki: https://cliqztix.atlassian.net/wiki/pages/viewpage.action?pageId=15892498. Or ask me
