### ISSUE TITLE
 add CLIQZ settings tab to browser preferences

### ISSUE THREAD

**Issue by chrmod** [cliqz-oss/browser-f#29]
Original issue: https://github.com/cliqz/browser-feedback/issues/11
Reporter: dominiks-cliqz

This is the place where (former) Firefox users come to look for settings and preferences: anything that is configurable about CLIQZ should thus be accessible from here.
![c1745bce-254d-11e5-9418-2935525c8b6e](https://cloud.githubusercontent.com/assets/1228153/10608140/fbc68940-773d-11e5-8918-a4b8dc930422.png)
(Or alternatively as tab from "Advanced".)

**Comment by richard-cliqz** [comment]
see #46 for more detailed specifications, closing this one.
