### ISSUE TITLE
Identify and replace prefs with marketing URL

### ISSUE THREAD

**Issue by chrmod-cliqz** [cliqz-oss/browser-f#3]
To reduce end-user confusion, we should point all content URLs to CLIQZ website.

**Comment by chrmod-cliqz** [comment]
Noticed on Windows 10 after update: https://www.mozilla.org/en-US/firefox/windows-10/welcome/?utm_source=firefox-browser&utm_medium=firefox-browser

**Comment by chrmod** [comment]
moved to jira
