### ISSUE TITLE
Crash report widget says firefox crashed, and sends the report to FF servers. 

### ISSUE THREAD

**Issue by chrmod** [cliqz-oss/browser-f#30]
Original issue: https://github.com/cliqz/browser-feedback/issues/4
Reporter: konark-cliqz

Screenshot : 
<img width="412" alt="4b14263e-24f9-11e5-95ea-11b6580c0c37" src="https://cloud.githubusercontent.com/assets/1228153/10608236/7113311c-773e-11e5-812c-c8b0cc345e81.png">
How to reproduce :

    ps -ef | grep Cliqz
    kill -ABRT process_id
    submit_report

**Comment by luciancor** [comment]
messaging fixed
