### ISSUE TITLE
Safe browsing (google hook)

### ISSUE THREAD

**Issue by richard-cliqz** [cliqz-oss/browser-f#31]
API doc: https://developers.google.com/safe-browsing/

From

    browser/app/profile/firefox.js

:

    978:pref("browser.safebrowsing.updateURL", "https://safebrowsing.google.com/safebrowsing/downloads?client=SAFEBROWSING_ID&appver=%VERSION%&pver=2.2&key=%GOOGLE_API_KEY%");
    989:pref("browser.safebrowsing.appRepURL", "https://sb-ssl.google.com/safebrowsing/clientreport/download?key=%GOOGLE_API_KEY%");

those wont work for us as we do not provide GOOGLE_API_KEY

**Comment by richard-cliqz** [comment]
From what I understand, Google Safe Browsing APIv3 is safe to use as it does not share any data with the server about visited websites.
Firefox does not use lookup API that sends urls to google.

Anyways to use Safe Browsing API we need to provide GOOGLE_API_KEY

**Comment by chrmod** [comment]
it is enabled by now via google api key used for geo location services. Need to verify though

**Comment by chrmod** [comment]
it seems it works. Use this URL as a test http://itisatrap.org/firefox/its-a-trap.html
