### ISSUE TITLE
Onboarding - First time experience

### ISSUE THREAD

**Issue by richard-cliqz** [cliqz-oss/browser-f#33]
We want users to have best first time experience with CLIQZ browser. Also we probably want them to think it is not Firefox.

    Those are some prefs that we can set:

    // Don't show 'know your rights' on first run
    pref("browser.rights.3.shown", true);

    // Don't show WhatsNew on first run after every update
    pref("browser.startup.homepage_override.mstone","ignore");

**Comment by chrmod** [comment]
@sean-cliqz please put onboarding related details on this issue

**Comment by stefanie-cliqz** [comment]
Update: The UX team created an onboarding concept that is being implemented by Panagiota. For internal reference see https://cliqztix.atlassian.net/browse/DBBD-58
