### ISSUE TITLE
Investigate build options differences

### ISSUE THREAD

**Issue by richard-cliqz** [cliqz-oss/browser-f#37]
while taking a look at about:buildconfig, you can identify some differences between our build and regular mozila one.

    Some of them:
    gcc: -ffunction-sections -fdata-sections

    configure arguments (on linux):

        --host=x86_64-linux-gnu
        --prefix=/usr
        --libexecdir=/usr/lib/firefox
        -with-l10n-base=/build/firefox_mU0NB/firefox-39.0+build5/./l10n
        -srcdir=/build/firefox_mU0NB/firefox-39.0+build5/.
        --enable-release
        --disable-install-strip
        --disable-updater
        --enable-startup-notification
        --with-distribution-id=com.ubuntu
        --enable-optimize
        --enable-tests
        --enable-crashreporter
        --disable-gnomevfs
        --enable-gio
        --disable-debug
        --disable-elf-hack
        --enable-gstreamer=1.0
        -with-google-api-keyfile=/build/firefox_mU0NB/firefox-39.0+build5/debian/ga
        -with-google-oauth-api-keyfile=/build/firefox_mU0NB/firefox-39.0+build5/debian/go

    no present in official:

        --enable-official-branding
        --with-app-name=CLIQZ
        --enable-update-packaging

Comments
Krzysztof added a comment - 05/Aug/15 10:18 AM

Firefox Windows options differences:

target
i686-pc-mingw32

conf:

    --enable-jemalloc
    --enable-eme=adobe
    --enable-require-all-d3dc-versions

**Comment by chrmod** [comment]
moved to jira
