### ISSUE TITLE
make sure cliqz@cliqz.com cannot be disabled by Mozilla blocklist

### ISSUE THREAD

**Issue by richard-cliqz** [cliqz-oss/browser-f#38]
after browser starts it calls a blocklist url
https://blocklist.addons.mozilla.org/blocklist/3/%7Bec8030f7-c20a-464f-9b0e-13a3a9e97384%7D/40.0/Firefox/20150807085045/WINNT_x86-msvc/es-ES/release/Windows_NT%206.2/default/default/2/15/3/

**Comment by chrmod** [comment]
@luciancor you know anything about blocklist?

**Comment by luciancor** [comment]
@chrmod @richard-cliqz firefox maintains a list of blacklisted addons. As long as cliqz is not there I think we should keep this link in place. We should make sure that cliqz@cliqz.com cannot be disabled in general

**Comment by chrmod** [comment]
Moving to backlog as it is not clear how or if we should go this way.

**Comment by chrmod** [comment]
moved to jira
