### ISSUE TITLE
top/burger menu --> addons: add a hint that cliqz browser users add-ons of the official Mozilla store

### ISSUE THREAD

**Issue by richard-cliqz** [cliqz-oss/browser-f#43]
CLIQZ uses add-ons of the official Mozilla repository - add a hint about that in about:addons --> get extensions

(English) „CLIQZ uses add-ons of the official Mozilla Firefox repository“

(German) „CLIQZ nutzt Add-ons aus dem offiziellen Mozilla Firefox Verzeichnis“

**Comment by chrmod** [comment]
we had it already with 0.8, so it must get lost with upgrade to Firefox 41
