### ISSUE TITLE
In top/ burger menu: Add the "Tipps and tricks" / "Tipps und Tricks" (DE) to the list of pre-set bookmarks 

### ISSUE THREAD

**Issue by richard-cliqz** [cliqz-oss/browser-f#44]
should lead to https://cliqz.com/home/cliqz-triqz (English/German dependent on Browser version)

**Comment by chrmod** [comment]
changes covered by extension

**Comment by richard-cliqz** [comment]
still missing in 0.8.2
(all OS)

**Comment by luciancor** [comment]
@richard-cliqz can you please update your extension to from https://cliqz.com/latestbeta and check again?
