### ISSUE TITLE
In top/ burger menu --> help/"questionmark":  Add the "CLIQZ tour" linkto re-view the CLIQZ onboarding tour

### ISSUE THREAD

**Issue by richard-cliqz** [cliqz-oss/browser-f#45]
should lead to chrome://cliqz/content/onboarding/onboarding.html (english version for english browser, German alike)

**Comment by chrmod** [comment]
changes covered by extension

**Comment by richard-cliqz** [comment]
still missing in 0.8.2 (all OS)
