### ISSUE TITLE
Browser options: All settings for CLIQZ's proprietary features to be included in the browser options

### ISSUE THREAD

**Issue by richard-cliqz** [cliqz-oss/browser-f#46]
Changes

A) From Q-Menu: Feedback & FAQ to be an own top-level preferences entry named "Support" (EN) / "Hilfe" (DE) featuring 2 things:

1) "Support and contact" / „Hilfe und Kontakt“ (former Feedback and FAQ)
(English) „Nadine from CLIQZ User Support is happy to help you. Get in touch with her!“ (link should have the functionality of the current Q-Menu entry, english version)
(German) „Nadine ist die Gute Fee bei CLIQZ. Sie freut sich auf Deine Fragen. Kontaktiere sie!“ (link should have the functionality of the current Q-Menu entry, German version)

2) "Tipps and tricks" / "Tipps und Tricks" (former CLIQZ Triqz)
(English) "With CLIQZ, you can use many shortcuts to find quick answers to your everyday questions! Just click here to see how!“ (Link with same functionality as Q-Menu entry, English Version)
(German) „Mit CLIQZ kannst Du viele Shortcuts benutzen um schnell Antworten auf Deine alltäglichen Suchen zu finden! Klicke hier um zu sehen wie es funktioniert!“ (Link with same functionality as Q-Menu entry, German Version)

B) Default Search engine -> already covered in preferences, no action necessary

C) Explicit content -> add in Preferences under Content, as dropdown-menu for the three options:
(English)
"Filter content"﻿
﻿﻿"Block websites with explicit content" <dropdown: always, always ask, never>

(German)
"Inhalte filtern"
"Webseiten mit nicht jugendfreien Inhalten blockieren" <dropdown: immer, immer fragen, niemals>﻿﻿

D) Share location ->  add in „Privacy“ as dropdown-menu
(English)
"Location data"﻿
﻿﻿"Use my position for location-based searches" <dropdown: always, always ask, no>

(German)
"Standortdaten"
"Zur Umgebungssuche meinen Standort erfassen" <dropdown: immer, immer fragen, niemals>﻿﻿

E) Human Web entry be added as a checkbox under "Privacy" according to the current Q-Menu entry (also with link to the HumanWeb paragraph on our website).

**Comment by chrmod** [comment]
moved to jira
