### ISSUE TITLE
Add a mechanism for AdBlock Plus users that automatically disables the AdBlocker when visiting BILD.de as long as BILD.de prevents AdBlock Plus users to see its content

### ISSUE THREAD

**Issue by richard-cliqz** [cliqz-oss/browser-f#48]
Flow for users (must have AdBlock Plus installed)

1) user navigates to Bild.de
2) a callout appears, asking the user whether we should de-activate AdBlock Plus while she is on bild.de, with options (i.e. 3 buttons) “always”, “always ask”, “no”
3) user sees bild.de content without barrier
4) going to another domain AdBlock Plus works normally
5) we add one additional entry to the Q-Menu in order to enable the user to change the settings made in 2).

Opt-in message to be triggered when navigating to bild.de
User should be able to see all BILD.de content normally as long as she is on the site
When leaving BILD.de, the ad blocker should again work as intended

**Comment by chrmod** [comment]
done in extension already - just update the extension version

**Comment by richard-cliqz** [comment]
Observation by Roberto (WIN 7, 8.1)
@luciancor 
1) there is no message on the top of the page, asking if CLIQZ should bypass the bild.de barrier
2) the yellow message appears only for a second and there’s not enough time to click on it

**Comment by luciancor** [comment]
@richard-cliqz it should be fixed in the next build of the browser. The version of extension was outdated in the old build

**Comment by alver-cliqz** [comment]
Can I ask - does we really need this? I don't like this third-party dependency in our product, it could be some potential problem in such kind of integration.

**Comment by luciancor** [comment]
not any more - we should take it out at the same time with addon blocking
