### ISSUE TITLE
v.1.10.0 does not build due to limited right on cliqz amazon cdn

### ISSUE THREAD

**Issue by milouse** [cliqz-oss/browser-f#523]
Hi!

The 1.10 tagged version build fails as we are not able to download the following file at build time : 

`https://s3.amazonaws.com/cdncliqz/update/browser_beta/https-everywhere/https-everywhere@cliqz.com-5.2.9-browser_beta-signed.xpi`

However, if I replace this url by the following in the `mozilla-release/config/rules.mk` file, everything goes fine : `https://s3.amazonaws.com/cdncliqz/update/browser/https-everywhere/https-everywhere@cliqz.com-5.2.9-browser-signed.xpi`

Please either open the browser_beta url to public or modify your `mozilla-release/config/rules.mk` to point to an accessible one. 

Thanks :)

**Comment by stefanie-cliqz** [comment]
Thanks @milouse. We'll look into the issue and get back to you.

**Comment by alver-cliqz** [comment]
Hi, @milouse. Just checked - both links works. Can you please re-check on your side?

**Comment by milouse** [comment]
Ok weird, I confirm both links works. But the beta one did not work last week. Did you change anything?

BTW, the most important thing is that it's working now.

**Comment by luciancor** [comment]
@milouse we had an issue with HTTPSEverywhere but it is fixed now. Thanks for your report!
