### ISSUE TITLE
Burger Menu --> questionmark AND top menu --> help: change wordings 

### ISSUE THREAD

**Issue by richard-cliqz** [cliqz-oss/browser-f#54]
"Feedback & FAQ" to "Support and contact" / „Hilfe und Kontakt“
CLIQZ Triqz to "Tipps and tricks" / "Tipps und Tricks"

**Comment by chrmod** [comment]
there was a recent change in the extension. Need to verify if it works in the browser

https://github.com/cliqz/navigation-extension/pull/1225
