### ISSUE TITLE
Browser publisher unknown on Windows

### ISSUE THREAD

**Issue by sam-cliqz** [cliqz-oss/browser-f#55]
Windows 8.1 Pro. Cliqz 41.0 en-US downloaded from cliqz.com.

![cliqz unknown pub](https://cloud.githubusercontent.com/assets/13136623/10630831/00978a54-77da-11e5-93f2-4643fbdb5c69.png)

@chrmod

**Comment by chrmod** [comment]
that's a know bug of current build, will be fixed very soon

**Comment by chrmod** [comment]
fixed by: https://github.com/cliqz-oss/browser-f/commit/37b972be432f81f016477acaa52dbd4fc602a2d7

had to move tag towards.
