### ISSUE TITLE
download from cliqz.com missleading message with typo + opens 3 tabs by default - middle one empty

### ISSUE THREAD

**Issue by richard-cliqz** [cliqz-oss/browser-f#56]
fresh profile, install from cliqz com: 3 tabs opened by default, middle one empty, typos in message at browser window bottom CLQZ for Firefox, plus the message is misleading in the context as I, as a user download the cliqz browser

![capture](https://cloud.githubusercontent.com/assets/6839735/10659325/49284446-789f-11e5-9a3e-f861876db6f8.PNG)

**Comment by richard-cliqz** [comment]
3 tabs opened is correct - 
1) cliqz homepage cliqz.com
2) about:home
3) cliqz onboarding tour

Issue was empty tab 2 - fixed.

**Comment by sean-cliqz** [comment]
@richard-cliqz Could you explain why opening 3 tabs is correct? Would it not be better to show one to focus the user's attention?
