### ISSUE TITLE
Paste long url and press enter, url out of the box

### ISSUE THREAD

**Issue by artem-cliqz** [cliqz-oss/browser-f#58]
Recipe to reproduce:
![long_url_issue1](https://cloud.githubusercontent.com/assets/13622775/10759099/b7b72ad4-7cb5-11e5-8888-14f77fe746d7.gif)

**Comment by chrmod** [comment]
seems to work well with new theme.

**Comment by stefanie-cliqz** [comment]
tested. Worked for me.
