### ISSUE TITLE
macOS: Keychain support

### ISSUE THREAD

**Issue by danielzuegner** [cliqz-oss/browser-f#627]
Hi all,

first of all: Thank you for this great browser!

As a Mac user the only thing that bugs me with CLIQZ is that I can't use passwords from my OS's keychain. There is an open source Firefox add-on that offers this functionality: [https://github.com/jfitzell/mozilla-keychain](https://github.com/jfitzell/mozilla-keychain)

I can understand that you don't want to enable add-ons in CLIQZ. However, I'd be happy to compile CLIQZ on my own and make some adjustments. These could either be:

- enable Plug-Ins in CLIQZ, or
- directly code the keychain functionality into CLIQZ.

Do you have some guidance which approach would be easier/better, and maybe point me to some parts in the code where I can make adjustments?

Thank you in advance. I hope I was clear, if not just ask me :-)

**Comment by alver-cliqz** [comment]
Good day, @danielzuegner.

Here two possible way to complete your task:
1. Allow back all extensions from Mozilla
2. Create your own certificate and add it to extensions installation process.

Please, look into this two commit to find our how you can process further:
https://github.com/cliqz-oss/browser-f/commit/f39933316cebdcd852346015ab30f56c5a30f549
https://github.com/cliqz-oss/browser-f/commit/a2be0c451e24544de095dc5acb392549a4d37d1c
https://github.com/cliqz-oss/browser-f/commit/1a3b8c00d75951a02e6ee3c91f9f1fadf7421081

**Comment by danielzuegner** [comment]
Hi @alver-cliqz,

Thank you very much for your reply. Thanks to your directions, I was able to compile CLIQZ with extensions allowed.

Best,

Daniel
