### ISSUE TITLE
Mac OS:  remove the FF version number and replace with Cliqz version number

### ISSUE THREAD

**Issue by richard-cliqz** [cliqz-oss/browser-f#64]
in applications --> Cliqz detail view
in notifier to update
![updater](https://cloud.githubusercontent.com/assets/6839735/10977199/01207ae0-83f0-11e5-8226-7964c06caee4.png)
![version_reg_mac](https://cloud.githubusercontent.com/assets/6839735/10977198/011f49f4-83f0-11e5-8aee-2ea701b7c4e9.png)

**Comment by richard-cliqz** [comment]
milestone: 0.8.3

**Comment by maxim-cliqz** [comment]
Version number in notification message comes from server XML in `updates/update@displayVersion`
