### ISSUE TITLE
WindowsOS: Please remove the FF version number in the list of installed software, and replace with Cliqz version number

### ISSUE THREAD

**Issue by richard-cliqz** [cliqz-oss/browser-f#65]
![win_reg](https://cloud.githubusercontent.com/assets/6839735/10977230/2cb0ca84-83f0-11e5-99bc-6abb8403be5d.jpg)

**Comment by richard-cliqz** [comment]
milestone 0.8.3

**Comment by alver-cliqz** [comment]
https://github.com/cliqz-oss/browser-f/pull/97
