### ISSUE TITLE
Remove the FF version number in “about:Cliqz”

### ISSUE THREAD

**Issue by richard-cliqz** [cliqz-oss/browser-f#66]
![capture](https://cloud.githubusercontent.com/assets/6839735/10977276/5d03504e-83f0-11e5-94be-1ab9c4a6bc8c.PNG)

**Comment by richard-cliqz** [comment]
milestone 0.8.3

**Comment by alver-cliqz** [comment]
PR https://github.com/cliqz-oss/browser-f/pull/91
