### ISSUE TITLE
Don't forget to create a new tag when an official version is released

### ISSUE THREAD

**Issue by milouse** [cliqz-oss/browser-f#686]
Other way to say: I've just discovered that the 1.15.0 version [seems to be released](http://repository.cliqz.com/?prefix=dist/debian-release/pool/main/c/cliqz/). Can you tag the corresponding commit to help repackaging? Thanks !

**Comment by remusao** [comment]
The version `1.15.0` has just been tagged. We will try to be more reactive for future versions. Thanks for the reminder.

**Comment by milouse** [comment]
No problem, it just eases the packaging for various other distributions.

Archlinux packages is out now :)
