### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by nyancat18** [cliqz-oss/browser-f#701]
host: manjaro testing 64 17.0.5

dependencies

python2 2.7.14

llvm 5.0.0-1

lld 5.0.0-1

clang 5.0.0-1

dbus-glib 0.108

m4 1.4.18-1

libxt 1.1.5

startup-notification 0.12-5

icu 59.1

autoconf2.13 2.13

gcc5 5.4.0-1

yasm 1.3.0-2

arch: 64 bit

ram: 16

cpu: fx 8350

buildscript
https://aur.archlinux.org/packages/cliqz/

log
https://p.teknik.io/Raw/1PNDA

**Comment by milouse** [comment]
Your compilation log doesn't seem to be complete. Do you really include all the lines?

Which version of gcc do you use? This package is tested successfully with gcc7, not gcc5. Can you try to install gcc7 before? Do you use the regular gcc version or the multilib?
