### ISSUE TITLE
CTRL + Z to reopen recently closed tab?

### ISSUE THREAD

**Issue by artem-cliqz** [cliqz-oss/browser-f#72]
Please consider having CTRL + Z to reopen recently closed tab.

CTRL + SHIFT + T works, but it's too much to remember for a user. I really like Safari's behaviour of doing it on CTRL + Z. It feels very intuitive to *undo* whatever I've done, including closing a tab.

**Comment by chrmod** [comment]
no go because of windows. Imagine CTRL+Z to open closed tab..
