### ISSUE TITLE
Disable history in private browsing mode

### ISSUE THREAD

**Issue by artem-cliqz** [cliqz-oss/browser-f#73]
Quite confusing to see one's history suggestions when using private browsing mode.

**Comment by sean-cliqz** [comment]
Most (maybe all) major browsers do this. I just tested Firefox, Chrome, and Safari and all show history and bookmarks in the dropdown when in a private window.

However, you are not the first to mention this. Perhaps there is room to rethink what "private" mode means to bring it more in line with what users might expect. We should keep this in mind as we experiment with what it means to be a privacy conscious browser, but in the short term, I think we should keep the established functionality.

**Comment by konark-cliqz** [comment]
@artem-cliqz @sean-cliqz : IMO what is also important is that none of them should save the history of what you browsed in the private mode, which looks like the case..

 Excerpt from Mozilla docs about private browsing : "Private Browsing allows you to browse the Internet without saving any information about which sites and pages you’ve visited."

**Comment by richard-cliqz** [comment]
Thank you for your comments.
I am closing this one for now, following @sean-cliqz 's and @konark-cliqz 's comments.
