### ISSUE TITLE
Home page is not set properly after installing browser over old version

### ISSUE THREAD

**Issue by sean-cliqz** [cliqz-oss/browser-f#76]
When installing CLIQZ browser over a previous (beta version), the home page is not correct. Resulting in this empty page at startup:
![2015-11-30 16 53 58](https://cloud.githubusercontent.com/assets/6603366/11507746/bb53b188-9855-11e5-9b1b-7f221c1549da.jpg)

**Comment by chrmod** [comment]
can we verify this one please @roberto-cliqz

**Comment by chrmod** [comment]
verified towards 0.9 beta - problem no longer exist
