### ISSUE TITLE
Buildconfig should not mention user folder name !

### ISSUE THREAD

**Issue by konark-cliqz** [cliqz-oss/browser-f#79]
Currently if you do ```about:buildconfig``` in Cliqzbrowser, the ```--configure arguments``` section has the flag  ```--with-google-api-keyfile=/Users/chrmod/jenkins/workspace/cfoxenmac/cfoxenmac/mozilla-release ```. IMO it should not mention /Users/{userName} but something more generic.

Screenshot attached:
<img width="1159" alt="screen shot 2015-12-06 at 23 01 01" src="https://cloud.githubusercontent.com/assets/10497229/11615893/f898cef0-9c6c-11e5-994b-6aa904d0eea9.png">

**Comment by stefanie-cliqz** [comment]
Next build system will include more generic naming. Closing this issue.
