### ISSUE TITLE
With human web activated, cliqz loops on error in console

### ISSUE THREAD

**Issue by milouse** [cliqz-oss/browser-f#792]
On linux, if you start cliqz from a terminal, and you have human web activated, even if the browser works as expected from a human being, it keeps outputing the same error stack in console:

```
Extension error: TypeError: windows is undefined moz-extension://9050a487-29ed-4a98-a87e-1bcf7f0df49c/modules/human-web/background.js 164
[[Exception stack
getAllOpenPages/</<@moz-extension://9050a487-29ed-4a98-a87e-1bcf7f0df49c/modules/human-web/background.js:164:9
Current stack
applySafeWithoutClone@resource://gre/modules/ExtensionCommon.jsm:285:133
wrapPromise/</<@resource://gre/modules/ExtensionCommon.jsm:466:15
withLastError@resource://gre/modules/ExtensionCommon.jsm:404:14
wrapPromise/<@resource://gre/modules/ExtensionCommon.jsm:460:11
]]
```

When I disable human web (both in cliqz panel and ghostery options the error stops.

**Comment by chrmod** [comment]
hi @milouse, thanks for the report. I will take a look into it. human-web has a set interval on which it operate background jobs, which seems to be the trigger. Still there should be no errors from it. @konark-cliqz maybe you know what is happening.

**Comment by milouse** [comment]
Yeah I assume it was caused by some interval execution. I was trying to debug my #668 issue and the console get polluted ;)

By the way I found a similar crash with ghostery, this time it happen only once or twice, no idea why or how to trigger it again, but is obviously related to the displaying of the purple box:

```
Extension error: TypeError: parent is undefined moz-extension://9050a487-29ed-4a98-a87e-1bcf7f0df49c/dist/purplebox.js 31
[[Exception stack
appendChild@moz-extension://9050a487-29ed-4a98-a87e-1bcf7f0df49c/dist/purplebox.js:31:4
createPurpleBox@moz-extension://9050a487-29ed-4a98-a87e-1bcf7f0df49c/dist/purplebox.js:342:3
handleMessages@moz-extension://9050a487-29ed-4a98-a87e-1bcf7f0df49c/dist/purplebox.js:442:5
Current stack
applySafeWithoutClone@resource://gre/modules/ExtensionCommon.jsm:285:133
asyncWithoutClone/<@resource://gre/modules/ExtensionCommon.jsm:1589:20
]]
```

**Comment by konark-cliqz** [comment]
Thank you for reporting the issues @milouse, 

Regarding the issue in Comment 0, 

```

**Comment by milouse** [comment]
Ow, you do work on saturday :( please enjoy your week-end, I can wait for monday :)

This is a custom build for archlinux, you have the recipe [here](https://aur.archlinux.org/packages/cliqz/). I didn't try with the debian build.

`about:support` tell the following version numbers:

## Application basics

Name | Cliqz
---- | ----
Version | 1.17.1
Build ID | 20171130123422

## Cliqz Features

name | version | id
---- | ---- | ----
Cliqz | 1.22.2 | `cliqz@cliqz.com`
HTTPS Everywhere | 2017.10.30 | `https-everywhere@cliqz.com`

## Extensions 

name | version | id
---- | ---- | ----
Ghostery | 7.3.3.7 | `firefox@ghostery.com`
