### ISSUE TITLE
Update history and change log discrepancy 

### ISSUE THREAD

**Issue by konark-cliqz** [cliqz-oss/browser-f#80]
I feel there is lot of discrepancy in the update history shown in Cliqz-browser and the change log that opens after clicking on details button.

1. For instance, the last update is Cliqz 41.0 security-update. Clicking on details takes to the ```https://cliqz.com/en/products/browser-changelog``` , where there is no change-log w.r.t 41.0 and none of the change logs mention any security update.

2. In my update history, the update that happened on 7th August, when clicked on details takes me to release post on ```https://www.mozilla.org/en-US/firefox/42.0/releasenotes/``` which got published on 3rd November 2015.

Screenshot:
<img width="373" alt="screen shot 2015-12-06 at 23 07 32" src="https://cloud.githubusercontent.com/assets/10497229/11615938/1b184c34-9c6e-11e5-9e28-caaec6ba6f56.png">

**Comment by chrmod** [comment]
moved to jira
