### ISSUE TITLE
Users can choose a start page

### ISSUE THREAD

**Issue by stefanie-cliqz** [cliqz-oss/browser-f#81]
Allow user to choose any website as a start page.
Where: Settings menu > Preferences > General

Note: we are aware of potential risks associated with this feature. We will start "open", learn more about the risks and then improve based on our learnings.

**Comment by stefanie-cliqz** [comment]
Discussed with @richard-cliqz, see description above. Please implement.

**Comment by chrmod** [comment]
@maxim-cliqz can you take care of it along with https://github.com/cliqz-oss/browser-f/issues/82

**Comment by maxim-cliqz** [comment]
Yep

**Comment by maxim-cliqz** [comment]
Done
