### ISSUE TITLE
User can choose between multiple browser start options

### ISSUE THREAD

**Issue by stefanie-cliqz** [cliqz-oss/browser-f#82]
The Cliqz browser currently opens the CLIQZ Start Page and additionally the tabs from the last session.

We would like to add more options in:

1. Show CLIQZ Start Page 
2. Show CLIQZ Start Page and windows and tabs from last session
3. Show blank page

Re: point 2 - this will open CLIQZ Start Page on first tab (start page) and websites from last session on the following tabs. See current behavior in CLIQZ browser.

**Comment by stefanie-cliqz** [comment]
As discussed and agreed on, solution is to add 2 checkboxes: "show CLIQZ start page" (checked by default) and "restore previous session" (not checked by default).

**Comment by maxim-cliqz** [comment]
Done

**Comment by luciancor** [comment]
from @roberto-cliqz 
- going to Settings >> Preferences >> General there are two checkboxes. The first one works: windows and tabs from the last time can be restored. But if both checkboxes are checked, the CLIQZ start page is not shown with the previous windows and tabs.

**Comment by chrmod** [comment]
moved to jira
