### ISSUE TITLE
On uninstall, change link to offboarding web page on cliqz.com

### ISSUE THREAD

**Issue by stefanie-cliqz** [cliqz-oss/browser-f#85]
When a user uninstalls the CLIQZ for Firefox add-on, they are directed to an offboarding web page on cliqz.com. The link currently directs German speaking users to the English page and therefore needs to be changed.

Correct link: *https://cliqz.com/home/offboarding*

(English version of page: https://cliqz.com/en/home/offboarding)

**Comment by chrmod** [comment]
it's fixed in current version of extension

**Comment by stefanie-cliqz** [comment]
Tested - works fine for me.
