### ISSUE TITLE
Shift + Home doesn't work in address bar

### ISSUE THREAD

**Issue by alver-cliqz** [cliqz-oss/browser-f#86]
Win8. Cliqz 0.8.2 (32 bit). If put cursor in the end of address bar and press Shift + Home text will not selected.

**Comment by stefanie-cliqz** [comment]
Hi @roberto-cliqz can you please test if this is fixed in the released beta version? Thanks!

**Comment by roberto-cliqz** [comment]
This is fixed in the released beta version.
