### ISSUE TITLE
CLIQZ extension in FF43+

### ISSUE THREAD

**Issue by luciancor** [cliqz-oss/browser-f#88]
Investigate how we could sign the extension ourselves and still keep the system safe.

**Comment by maxim-cliqz** [comment]
Signature verification is done in `toolkit/mozapps/extensions/internal/XPIProvider.jsm`, by using functions from `nsIX509CertDB` (`openSignedAppFileAsync`, `verifySignedDirectoryAsync`, ...).
Those functions accept certificate root ID to check the signature against. From what I've seen, two may be used: `AddonsPublicRoot` and `AddonsStageRoot`.
Seems, we should be done by putting our certificate to be used as those roots.

**Comment by maxim-cliqz** [comment]
Those two certificates are located in `security/apps/` directory and are named `addons-public.crt` and `addons-stage.crt` respectively.

**Comment by luciancor** [comment]
@maxim-cliqz came across an interesting link today - http://olympia.readthedocs.org/en/latest/topics/api/signing.html - maybe it helps for this task :)

**Comment by maxim-cliqz** [comment]
Hmmm, seems it's about signing with Mozilla's certificate.
Several years ago at Yandex I was using a ruby script to sign addon. Unfortunately I completely forgot where I took it. But it definitely was somewhere on the Internet.

**Comment by maxim-cliqz** [comment]
Found the script. Here it is: https://adblockplus.org/blog/signing-firefox-extensions-with-python-and-m2crypto
There's also another solution, which uses signtool from Mozilla's nss library: https://www.mozdevgroup.com/docs/pete/Signing-an-XPI.html

**Comment by luciancor** [comment]
@maxim-cliqz 

"Valid add-on signing certificates must be issued from a Mozilla master certificate"* so it seems that we need to create a certificate for each extension from a master certificate. This fill fix the "aCert.commonName" issue.

* https://docs.google.com/document/d/1KhpDteoHFmVRkzlrT8v0N3F-KrPxLoZFM3mWmEmOses/edit#heading=h.31365qykqlul

**Comment by luciancor** [comment]
"There are several ways to install add-ons from the local machine such as bundled with the install directory or through the windows registry. None of these locations or mechanisms will change except for the new requirement that the .xpi archives be signed with a Mozilla-issued certificate **containing a matching add-on ID.**"

**Comment by maxim-cliqz** [comment]
Mozilla uses this algorithm to sign XPIs: http://lia.deis.unibo.it/Misc/SW/Java/java1.7/technotes/tools/solaris/jarsigner.html
Their only seeming difference is that .SF file must contain only one entry (except "Signature-Version"): "SHA1-Digest-Manifest", which holds SHA1 digest of the .MF file in Base64 encoding.

**Comment by maxim-cliqz** [comment]
Good manual about running an own CA: https://jamielinux.com/docs/openssl-certificate-authority/index.html

**Comment by maxim-cliqz** [comment]
I think it's done now.
