### ISSUE TITLE
Launch 0.9 Update

### ISSUE THREAD

**Issue by stefanie-cliqz** [cliqz-oss/browser-f#90]
- related to https://github.com/cliqz-oss/browser-f/issues/64 and https://github.com/cliqz-oss/browser-f/issues/65

**Comment by alver-cliqz** [comment]
Need to replace version in repack\distribution\distribution.ini and mozilla-release\browser\config\version_display.txt to 0.9

**Comment by maxim-cliqz** [comment]
Set version to 0.9 in `update.xml` on server

**Comment by chrmod** [comment]
0.9 beta release started

**Comment by chrmod** [comment]
moved to jira
