### ISSUE TITLE
Silverlight plugin

### ISSUE THREAD

**Issue by chrmod** [cliqz-oss/browser-f#92]
Netflix and other popular websites require Silverlight plugin to play videos on windows browser. 

We should investigate what are the possibilities to bundle it with CLIQZ browser. 

@alver-cliqz @maxim-cliqz do you have any experience with it?

**Comment by alver-cliqz** [comment]
Not yet. As i see - this is usual NPAPI plugin. Installer is 6 Mb for 32-bit system and 12 Mb for 64-bit. Files are installed into c:\Program Files\Microsoft Silverlight\ and c:\Program Files (x86)\Microsoft Silverlight\ (on 64-bit system), installer needs admin rights to do this. After install process complete, user get a lot of files + some kind of autoupdate system, so looks like it better to distribute Silverlight as original installer. For example, add an option "Install Silverlight" in our installer and after our install complete automatically download and run Silverlight installer in silence mode.

**Comment by chrmod** [comment]
It seems we that we cannot distribute Silverlight with our application bundle due to its license constraints on publishing: http://www.microsoft.com/getsilverlight/get-started/install/license-win.aspx

Other then installing Silverlight during CLIQZ installation we can detect if it is needed and help user to install it - note that it requires super user privileges.

**Comment by stefanie-cliqz** [comment]
Should not bundle Silverlight with CLIQZ due to large size of Silverlight installer and others. Other options to make it easier for users to use Silverlight may be explored in the future. At this point, installing it manually should not be too difficult.
