### ISSUE TITLE
Check if Browser Logo is still hidden after installation

### ISSUE THREAD

**Issue by stefanie-cliqz** [cliqz-oss/browser-f#94]
Reported by @thuy-cliqz on Aug. 31 on https://github.com/cliqz/bug-tracker/issues/771:

"My logo was not on the desktop after installation.
IMO, this can lead to not using the browser for most users encounting the same behaviour of the logo.
Bottom line: we need to make sure the logo is added to the frequently-used area on the device.
Experienced on Mac."

**Comment by stefanie-cliqz** [comment]
@roberto-cliqz would you please try to reproduce and confirm it's still an issue? Thanks!

**Comment by roberto-cliqz** [comment]
After installation the user is asked to drag CLIQZ browser in the application folder as usual. Keeping the logo in the dock, in a frequently-used area on the device or on the desktop is up to the user's will.

**Comment by stefanie-cliqz** [comment]
Okay, thanks. Will close because this is in accordance to Mac behavior. We may consider doing something about the underlying issue (making CLIQZ more visible to the user right after installation), but will not address this now.
