### ISSUE TITLE
Refactor cliqz.cfg

### ISSUE THREAD

**Issue by maxim-cliqz** [cliqz-oss/browser-f#95]
Move css rules to a more appropriate location.

**Comment by chrmod** [comment]
ATM autoconfig is a proper place to keep "those" CSS rules. In future we may want to move into better place. 

Also it should not be a part of 0.9

**Comment by maxim-cliqz** [comment]
@chrmod problem is #82 slightly depends on it. And I'm into it already anyway.

**Comment by chrmod** [comment]
@maxim-cliqz Please submit a WIP PR so we can discuss common approach for this issue.

**Comment by maxim-cliqz** [comment]
done https://github.com/cliqz-oss/browser-f/pull/96
